services:
  apache:
    build:
      context: .
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      # ドキュメントルート
      - ./htdocs:/usr/local/apache2/htdocs
      # アクセスログ
      - ./logs/:/usr/local/apache2/logs
