# https://gallery.ecr.aws/docker/library/httpd
FROM public.ecr.aws/docker/library/httpd:2.4.65-alpine3.22

RUN apk update && \
    apk add --no-cache apache2 && \
    rm -rf /var/cache/apk/*

# 必要に応じて、Apache用の設定ファイルを上書き
# COPY .conf/httpd.conf /etc/httpd/conf/httpd.conf

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]